language: python
python:
  - '3.6'
  - '3.5'
  - '3.4'
  - '2.7'
services:
  - mysql
  - postgresql
env:
  - 'DATABASE_URL=sqlite:///:memory:'
  - DATABASE_URL=postgresql+psycopg2://postgres@127.0.0.1/dataset
  - DATABASE_URL=mysql+pymysql://root@127.0.0.1/dataset?charset=utf8
install:
  - pip install -U pip wheel
  - pip install flake8 psycopg2 PyMySQL nose
  - pip install -e .
before_script:
  - sh -c "if [ '$DATABASE_URL' = 'postgresql+psycopg2://postgres@127.0.0.1/dataset' ]; then psql -c 'DROP DATABASE IF EXISTS dataset;' -U postgres; fi"
  - sh -c "if [ '$DATABASE_URL' = 'postgresql+psycopg2://postgres@127.0.0.1/dataset' ]; then psql -c 'create database dataset;' -U postgres; fi"
  - sh -c "if [ '$DATABASE_URL' = 'mysql+pymysql://root@127.0.0.1/dataset?charset=utf8' ]; then mysql -e 'create database IF NOT EXISTS dataset DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'; fi"
script:
  - flake8 --ignore=E501,E123,E124,E126,E127,E128 dataset test
  - nosetests -v
cache:
  directories:
    - $HOME/.cache/pip
