---
language: python
python:
- '3.3'
- '2.7'
- '2.6'
env:
- DATABASE_URL=sqlite:///:memory:
- DATABASE_URL=postgresql+psycopg2://postgres@127.0.0.1/dataset
- DATABASE_URL=mysql+mysqlconnector://travis@127.0.0.1/dataset?charset=utf8
install:
- pip install --allow-external mysql-connector-python mysql-connector-python flake8 psycopg2
before_script:
- sh -c "if [ '$DATABASE_URL' = 'postgresql+psycopg2://postgres@127.0.0.1/dataset' ]; then psql -c 'DROP DATABASE IF EXISTS dataset;' -U postgres; fi"
- sh -c "if [ '$DATABASE_URL' = 'postgresql+psycopg2://postgres@127.0.0.1/dataset' ]; then psql -c 'create database dataset;' -U postgres; fi"
- sh -c "if [ '$DATABASE_URL' = 'mysql+mysqlconnector://travis@127.0.0.1/dataset?charset=utf8' ]; then mysql -e 'create database IF NOT EXISTS dataset DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'; fi"
script:
- flake8 --ignore=E501,E123,E124,E126,E127,E128 dataset test
- python setup.py test
